# Generated by Django 3.0.4 on 2020-08-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200728_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='dto',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dto',
        ),
    ]
