# Generated by Django 3.0.4 on 2020-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200803_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='end_credit',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Coste'),
        ),
    ]
